name: open_store
description: Simple lightweight package to open store page for android and iOS GooglePlay and AppStore
version: 0.4.0
homepage: https://github.com/Frezyx/open_store

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.6
  talker: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
